# Container for starting a cli for build commands
# Usage: docker-compose -f build.yml run cli
cli:
  image: phase2/devtools-build:php70
  working_dir: /var/www
  command: /bin/bash
  volumes:
    - .:/var/www/
  external_links:
    - drupal8_db:db

# Container for running drush in the docroot.
# Usage: docker-compose -f build.yml run drush <command>
# Where <command> is a direct drush command like cache-rebuild
drush:
  image: phase2/devtools-build:php70
  entrypoint: [ "/init", "drush" ]
  working_dir: /var/www/build/html
  volumes:
    - .:/var/www/
  external_links:
    - drupal8_db:db

# Container for running grunt in the docroot.
# Usage: docker-compose -f build.yml run grunt <command>
grunt:
  image: phase2/devtools-build:php70
  entrypoint: [ "/init", "grunt" ]
  working_dir: /var/www
  volumes:
    - .:/var/www/
  external_links:
    - drupal8_db:db

# Usage: docker-compose -f build.yml run composer <command>
composer:
  image: phase2/devtools-build:php70
  entrypoint: [ "/init", "composer" ]
  working_dir: /var/www
  command: composer update --prefer-dist
  volumes:
    - .:/var/www/

# Usage: docker-compose -f build.yml run composer-install
# Use this pattern if you want to strictly control the options to a command
composer-install:
  image: phase2/devtools-build:php70
  working_dir: /var/www
  command: composer install --prefer-dist
  volumes:
    - .:/var/www/
